.scf_source_files <- Filter(Negate(is.null), lapply(sys.frames(), function(frame) frame$ofile))
.scf_source_file <- if (length(.scf_source_files)) tail(.scf_source_files, 1)[[1]] else NULL
.scf_cli_file <- grep("^--file=", commandArgs(FALSE), value = TRUE)
.scf_start_dir <- if (!is.null(.scf_source_file)) dirname(normalizePath(.scf_source_file)) else if (length(.scf_cli_file)) dirname(normalizePath(sub("^--file=", "", .scf_cli_file[[1]]))) else getwd()
source(file.path(.scf_start_dir, "../../..", "00_Settings/00_setup_R.R"))
scf_check_R_packages(c("Biobase", "Mfuzz", "e1071", "dplyr", "purrr", "reshape2", "ComplexHeatmap"))
suppressPackageStartupMessages({library(Biobase);library(Mfuzz);library(dplyr);library(purrr);library(reshape2);library(ComplexHeatmap)})
root <- normalizePath(file.path(.scf_start_dir, "../../.."), winslash = "/")
panel <- normalizePath(file.path(.scf_start_dir, ".."), winslash = "/")
plot_data <- file.path(panel, "03_PlotData")
dir.create(plot_data, showWarnings = FALSE)
source(file.path(.scf_start_dir, "01_define_expression_clustering.R"))
stage_means <- read.csv(file.path(root, "00_Global_Data/Shared_Inputs/Main_Figure_02/e_M02e/M02e_PBMC_Five_Stage_Mean_TPM.csv"), row.names = 1, check.names = FALSE)
cm <- clusterData(exp = stage_means, scaleData = TRUE, cluster.method = "mfuzz", cluster.num = 16)
saveRDS(cm, file.path(plot_data, "PBMC_16_Modules.rds"))
write.csv(as.data.frame(table(cm$wide.res$cluster)), file.path(plot_data, "PBMC_Module_Gene_Counts.csv"), row.names = FALSE)
